### ISSUE TITLE
Weiter Lösungen

### ISSUE THREAD

**Issue by musdasch** [streusselhirni/hfict-he17-oop1-aufgaben#1]
Ich bin auch dabei meine Lösungen auf github zu stelle ich habe dich in meinem README erwend fals es dich nicht stört. [Repo](https://github.com/musdasch/PG-HF-ICT)

**Comment by streusselhirni** [comment]
Absolut kein Problem. Ich werde wohl dasselbe noch nachtragen.

**Comment by streusselhirni** [comment]
Habe die README erweitert und u.a. auch auf dein Repo verwiesen.
