### ISSUE TITLE
Aufgabe 12

### ISSUE THREAD

**Issue by musdasch** [streusselhirni/hfict-he17-oop1-aufgaben#2]
Die crypt funktion kann nicht mit negativen Zahlen umgehen.

Key = -1
Wort = A
Output = @ 

Wenn du deine Programm noch um negative Zahlen erweitern wildst, kannst du das Komplement bilden.

Funktion:
```c++
/**
 * Finds the complement
 * @param  value number
 * @param  range range in which the number operates.
 * @return       complement
 */
int complement(int value, int range){
	value = sqrt(pow(value, 2));
	value = range - value;

	return value;
}
```
In der Main:
```c++
cout << "Schluessel eingeben: ";
cin >> key;

if(0 > key){
	key = complement(key, 26);
}
```
Gruss
Musdasch

**Comment by streusselhirni** [comment]
Kann das Problem nicht reproduzieren. Wenn ich `-2` als Schlüssel und `cde` als String eingebe, erhalte ich den korrekten String `abc` zurück.

**Comment by musdasch** [comment]
Sobald du `abc` und als schlüssel eingibst und den Schlüssel `-1` verwendest, erhälst du den String `@ab`, der korrekte String währe `zab`.

Dieser Issue ist nur zur Information für die die diesen Issue lesen und es für sich selbst lösen wollen. Kann also gleich wider geschlossen werden.
